#!/bin/bash
#59 */1 * * * bash /home/ec2-user/git/MyCalculator/my_script3 > /home/ec2-user/docs/my_script3.log

now=$(date +"%Y%m%d%H")
current_f=/home/ec2-user/docs/source_current/*.txt
arc_folder=/home/ec2-user/docs/source_archive/input_$now.tar.gz
tar cvzf $arc_folder $current_f
rm $current_f
