#!/bin/bash
#00 */1 * * * bash /home/ilya/bin/my_script3 > /home/ilya/bin/my_script3.log

now=$(date +"%Y%m%d%H")
cur_folder=/home/ilya/docs/source_current
arc_folder=/home/ilya/docs/source_archive
f_n=input_$now.tar.gz
cd $cur_folder 
tar -zcvf $f_n *.txt
mv $f_n $arc_folder
rm $cur_folder/*.txt
