#!/bin/bash
#05 */2 * * * bash /home/ec2-user/git/MyCalculator/my_script2 > /home/ec2-user/docs/my_script2.log

now=$(date +"%Y%m%d%H")
target_file=/home/ec2-user/docs/source_current/input_C_$now.txt

echo $[ 1 + $[ RANDOM % 1000000]] >> $target_file



