#!/bin/bash
#59 */1 * * * bash /home/ec2-user/git/MyCalculator/my_script3 > /home/ec2-user/git/MyCalculator/my_script3.log

now=$(date +"%Y%m%d%H")
cur_folder=/home/ec2-user/docs/source_current
arc_folder=/home/ec2-user/docs/source_archive
f_n=input_$now.tar.gz
cd $cur_folder
tar -zcvf $f_n *.txt
mv $f_n $arc_folder
rm $cur_folder/*.txt
