#!/bin/bash
#*/5 * * * * bash /home/ilya/bin/my_script > /home/ilya/Documents/bashGen/my_script.log

echo $[ 1 + $[ RANDOM % 100]] >> /home/ilya/Documents/bashGen/input1.txt
echo $[ 1 + $[ RANDOM % 100]] >> /home/ilya/Documents/bashGen/input2.txt
