#!/bin/bash
#*/5 * * * * bash /home/ec2-user/git/MyCalculator/MyCalculator/my_script > /home/ec2-user/docs/my_script.log

echo $[ 1 + $[ RANDOM % 1000]] >> /home/ec2-user/docs/input1.txt
echo $[ 1 + $[ RANDOM % 1000]] >> /home/ec2-user/docs/input2.txt
